name: ci_flow
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      - name: Build the Spring Boot JAR
        run: ./mvnw clean package
        working-directory: server
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Change to a different directory
        run: cd server
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
